# Jekyll configuration

name: Reconfig.IO
title: A Nifty Collection of Tales & PoC
description: A Nifty Collection of Tales & PoC
summary_image: /assets/images/default-card.png

# Url is currently only used only for the RSS feed in feed.xml
url: http://reconfig.io

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Evan Custodio
copyright: 2018

share:
  twitter: true

social:
  twitter: defparam
  github: defparam
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-118993985-1



# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: streetturtle
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3



markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
